[project]
name = "mf2000"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64", "osx-64"]
version = "1.19.01"

[dependencies]
filelock = "*"
meson = ">=1.3.1"
ninja = "*"
modflow-devtools = "*"

[tasks]

# meson build for mf2000
clean = { cmd = "rm -rf builddir" }
setup = { cmd = "meson setup --prefix=$(pwd) --bindir=bin builddir", env = { PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig", LIB = "$CONDA_PREFIX/Library/lib" } }
build = "meson install -C builddir"

# test mf2000
test = { cmd = "meson test --verbose --no-rebuild -C builddir version" }

# get ostag for system
get-ostag = { cmd = "python -c 'from modflow_devtools.ostags import get_ostag; print(get_ostag())'"}
